# Generated by Django 3.2.25 on 2025-07-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in currency (required if selling)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='action_type',
            field=models.CharField(choices=[('Donate', 'Donate'), ('Exchange', 'Exchange'), ('Request', 'Request'), ('Sell', 'Sell')], max_length=10),
        ),
    ]
